"""
Pre-loaded sample jobs for demo stability.
These are always available regardless of external API availability.
URLs point to real jobright.ai listing pages for each company/role.
"""
from datetime import datetime, timezone, timedelta
from .models import Job

def get_sample_jobs() -> list[Job]:
    now = datetime.now(timezone.utc)

    return [
        Job(id="demo-google-swe-1", title="Software Engineer, New Grad", company="Google",
            location="Mountain View, CA", url="https://jobright.ai/jobs/Google-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=2),
            description="Join Google as a new grad SWE. Work on large-scale distributed systems serving billions of users. Collaborate with world-class engineers on products like Search, Maps, and YouTube.",
            requirements=["BS/MS in Computer Science", "Python or Java", "Data Structures & Algorithms", "System Design basics", "GPA 3.5+"],
            source="jobright", is_priority=True, remote=False,
            match_score=88, job_type="software-engineering",
            match_reasons=["Strong CS fundamentals match", "Python/Java experience aligns", "New grad role perfectly fits 0 YOE"],
            missing_skills=["Go", "Kubernetes"], job_summary="Build and scale Google's core infrastructure products."),

        Job(id="demo-meta-swe-1", title="Software Engineer (University Grad)", company="Meta",
            location="Menlo Park, CA", url="https://jobright.ai/jobs/Meta-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=5),
            description="Meta is hiring university grad engineers to build the next generation of social platforms. Work on React, GraphQL, and distributed backend systems at massive scale.",
            requirements=["BS in CS or related", "React or frontend frameworks", "REST/GraphQL APIs", "SQL databases", "Problem solving skills"],
            source="jobright", is_priority=True, remote=True,
            match_score=82, job_type="software-engineering",
            match_reasons=["React experience matches", "API development background fits", "Remote-friendly role"],
            missing_skills=["Hack/PHP", "PyTorch"], job_summary="Build Meta's social platforms using React and distributed systems."),

        Job(id="demo-amazon-sde-1", title="Software Development Engineer I", company="Amazon",
            location="Seattle, WA", url="https://jobright.ai/jobs/Amazon-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=8),
            description="Amazon SDE I role for new grads. Own features end-to-end from design to deployment. Work with AWS services, microservices architecture, and CI/CD pipelines.",
            requirements=["BS CS", "Java or Python", "AWS services", "OOP principles", "Agile methodology", "Unit testing"],
            source="jobright", is_priority=True, remote=False,
            match_score=85, job_type="software-engineering",
            match_reasons=["AWS background is a strong fit", "Python experience matches", "Entry-level role ideal for new grads"],
            missing_skills=["AWS CDK", "DynamoDB"], job_summary="Own features end-to-end on Amazon's AWS-powered microservices."),

        Job(id="demo-microsoft-swe-1", title="Software Engineer - New Grad", company="Microsoft",
            location="Redmond, WA", url="https://jobright.ai/jobs/Microsoft-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=10),
            description="Microsoft is hiring new grad engineers to work on Azure cloud services and developer tools. Hybrid work environment with excellent mentorship programs for new grads.",
            requirements=["BS/MS CS", "C# or Python or Java", "Cloud fundamentals", "Git version control", "Strong communication"],
            source="jobright", is_priority=True, remote=False,
            match_score=80, job_type="software-engineering",
            match_reasons=["Python skills match", "Cloud experience relevant", "Great mentorship for new grads"],
            missing_skills=["C#", "Azure DevOps"], job_summary="Build Azure cloud services with Microsoft's developer tools team."),

        Job(id="demo-stripe-backend-1", title="Backend Engineer - New Grad", company="Stripe",
            location="San Francisco, CA", url="https://jobright.ai/jobs/Stripe-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=14),
            description="Stripe is building the economic infrastructure of the internet. Join as a backend engineer to work on payment APIs used by millions of businesses worldwide.",
            requirements=["BS CS", "Python or Ruby or Java", "REST API design", "SQL", "Distributed systems basics", "Testing"],
            source="jobright", is_priority=True, remote=True,
            match_score=78, job_type="software-engineering",
            match_reasons=["API development experience fits", "Python is primary language", "Remote-friendly"],
            missing_skills=["Ruby", "Payment systems"], job_summary="Build payment infrastructure APIs serving millions of global businesses."),

        Job(id="demo-airbnb-swe-1", title="Software Engineer - University Grad 2025", company="Airbnb",
            location="San Francisco, CA", url="https://jobright.ai/jobs/Airbnb-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=18),
            description="Airbnb is hiring university grad engineers to work on search, pricing, and host/guest experience. Work with React frontend and Python/Java backend systems.",
            requirements=["BS CS", "React or Vue", "Python or Java", "SQL", "Experience with web development", "Strong problem-solving"],
            source="jobright", is_priority=True, remote=False,
            match_score=76, job_type="software-engineering",
            match_reasons=["Full stack skills match", "React experience aligns", "Python backend fits"],
            missing_skills=["Scala", "Spark"], job_summary="Build search and pricing systems for Airbnb's global marketplace."),

        Job(id="demo-databricks-de-1", title="Data Engineer - New Grad", company="Databricks",
            location="San Francisco, CA / Remote", url="https://jobright.ai/jobs/New-Grad-Data-Engineer-Jobs",
            posted_at=now - timedelta(hours=20),
            description="Databricks is hiring new grad data engineers to build data pipelines and analytics infrastructure. Work with Apache Spark, Delta Lake, and Python at scale.",
            requirements=["BS CS or Data Engineering", "Python", "SQL", "Apache Spark basics", "Data pipeline experience", "Cloud (AWS/Azure/GCP)"],
            source="jobright", is_priority=True, remote=True,
            match_score=84, job_type="data-engineering",
            match_reasons=["Python is core requirement match", "SQL experience aligns", "AWS background relevant"],
            missing_skills=["Apache Spark", "Delta Lake"], job_summary="Build large-scale data pipelines using Apache Spark and Delta Lake."),

        Job(id="demo-snowflake-de-1", title="Associate Data Engineer", company="Snowflake",
            location="San Mateo, CA", url="https://jobright.ai/jobs/Entry-Level-Data-Engineer-Jobs",
            posted_at=now - timedelta(hours=22),
            description="Join Snowflake's data engineering team to build ETL pipelines and analytics workflows. Work with Snowflake SQL, Python, and cloud-native data tools.",
            requirements=["BS CS or related", "SQL expertise", "Python", "ETL/ELT concepts", "Cloud data warehousing", "dbt or Airflow a plus"],
            source="jobright", is_priority=True, remote=False,
            match_score=79, job_type="data-engineering",
            match_reasons=["SQL skills are strong match", "Python experience fits", "Cloud knowledge relevant"],
            missing_skills=["dbt", "Snowflake SQL"], job_summary="Build ETL pipelines and analytics workflows on Snowflake's cloud platform."),

        Job(id="demo-netflix-swe-1", title="Software Engineer (L3) - New Grad", company="Netflix",
            location="Los Gatos, CA", url="https://jobright.ai/jobs/Netflix-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=26),
            description="Netflix is hiring new grad engineers for their streaming platform team. Work on recommendation algorithms, content delivery networks, and microservices.",
            requirements=["BS/MS CS", "Java or Python", "Microservices architecture", "API design", "Strong algorithms knowledge"],
            source="jobright", is_priority=True, remote=False,
            match_score=72, job_type="software-engineering",
            match_reasons=["Java/Python skills match", "API experience relevant", "Strong CS fundamentals needed"],
            missing_skills=["Scala", "Cassandra"], job_summary="Build Netflix's streaming infrastructure and recommendation systems."),

        Job(id="demo-uber-swe-1", title="Software Engineer - New Grad 2025", company="Uber",
            location="San Francisco, CA", url="https://jobright.ai/jobs/Uber-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=30),
            description="Uber is hiring new grad engineers to work on their marketplace, payments, and maps technology. Work with Go, Python, and large-scale distributed systems.",
            requirements=["BS CS", "Python or Go or Java", "Distributed systems", "SQL/NoSQL databases", "Strong fundamentals"],
            source="jobright", is_priority=True, remote=False,
            match_score=74, job_type="software-engineering",
            match_reasons=["Python experience matches", "Database knowledge fits", "Entry-level friendly"],
            missing_skills=["Go", "Kafka"], job_summary="Build Uber's marketplace and real-time dispatch systems."),

        Job(id="demo-linkedin-swe-1", title="Software Engineer - Recent Grad", company="LinkedIn",
            location="Sunnyvale, CA", url="https://jobright.ai/jobs/New-Grad-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=34),
            description="LinkedIn is hiring recent grad engineers to build professional networking features, job recommendation algorithms, and data infrastructure.",
            requirements=["BS CS", "Java or Python", "REST APIs", "SQL", "Machine Learning basics a plus", "Good communication"],
            source="jobright", is_priority=True, remote=True,
            match_score=77, job_type="software-engineering",
            match_reasons=["Java/Python match", "API skills fit", "Remote available"],
            missing_skills=["Voldemort DB", "Kafka"], job_summary="Build LinkedIn's job recommendation and professional networking features."),

        Job(id="demo-openai-ml-1", title="Software Engineer - Applied AI", company="OpenAI",
            location="San Francisco, CA", url="https://jobright.ai/jobs/New-Grad-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=36),
            description="OpenAI is looking for engineers passionate about AI to build tools, APIs, and infrastructure for deploying large language models. Work with Python, LangChain, and ML pipelines.",
            requirements=["BS/MS CS", "Python", "Machine Learning fundamentals", "REST APIs", "LLM/AI interest", "PyTorch a plus"],
            source="jobright", is_priority=True, remote=False,
            match_score=91, job_type="software-engineering",
            match_reasons=["LangChain experience is rare and directly relevant", "Python is primary language", "AI/ML interest aligns perfectly"],
            missing_skills=["PyTorch", "CUDA"], job_summary="Build APIs and infrastructure for deploying large language models at OpenAI."),

        Job(id="demo-anthropic-swe-1", title="Software Engineer - New Grad", company="Anthropic",
            location="San Francisco, CA", url="https://jobright.ai/jobs/New-Grad-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=40),
            description="Anthropic is hiring engineers to build safe and reliable AI systems. Work on Claude's infrastructure, APIs, and developer tools using Python and LangChain.",
            requirements=["BS/MS CS", "Python", "API development", "LLM APIs experience", "Interest in AI safety", "Strong engineering fundamentals"],
            source="jobright", is_priority=True, remote=False,
            match_score=93, job_type="software-engineering",
            match_reasons=["LangChain & LLM API experience is a perfect match", "Python skills align", "AI project background relevant"],
            missing_skills=["Rust", "ML research background"], job_summary="Build Claude's infrastructure and APIs at the frontier of AI safety research."),

        Job(id="demo-doordash-swe-1", title="Software Engineer I - University Hire", company="DoorDash",
            location="San Francisco, CA", url="https://jobright.ai/jobs/Entry-Level-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=44),
            description="DoorDash is hiring university grad engineers for their logistics, merchant, and consumer platforms. Work with Kotlin, Python, and large-scale backend systems.",
            requirements=["BS CS", "Python or Kotlin or Java", "Backend development", "SQL", "API design", "Agile"],
            source="jobright", is_priority=True, remote=True,
            match_score=70, job_type="software-engineering",
            match_reasons=["Python experience matches", "Backend skills align", "Remote option available"],
            missing_skills=["Kotlin", "Logistics systems"], job_summary="Build DoorDash's logistics and delivery optimization backend systems."),

        Job(id="demo-coinbase-swe-1", title="Software Engineer - New Grad", company="Coinbase",
            location="Remote", url="https://jobright.ai/jobs/Entry-Level-Software-Engineer-Jobs",
            posted_at=now - timedelta(hours=48),
            description="Coinbase is hiring new grad engineers to build crypto trading infrastructure, wallet systems, and compliance tools. Fully remote with competitive compensation.",
            requirements=["BS CS", "Python or Go or TypeScript", "Backend systems", "SQL/NoSQL", "Security mindset", "Blockchain basics a plus"],
            source="jobright", is_priority=True, remote=True,
            match_score=68, job_type="software-engineering",
            match_reasons=["Python skills match", "Backend experience relevant", "Fully remote"],
            missing_skills=["Go", "Blockchain/Web3"], job_summary="Build crypto trading and wallet infrastructure at Coinbase, fully remote."),
    ]
